project:
  type: website
  output-dir: docs
  
website:
  title: "Nathan Bresette"
  navbar:
    right:
      - href: aboutme_index.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: consulting.qmd
        text: Consulting
      - href: datafest.qmd
        text: DataFest
      - href: Resume.qmd
        text: Resume

  page-footer:
    center:
      - icon: linkedin
        text: LinkedIn  
        href: https://linkedin.com
    left:
      - icon: phone
        text: 816-969-0150    
    right:
      - icon: envelope
        text: nathanbresette04@gmail.com

format:
  html:
    theme: Pulse
    css: styles.css
    toc: true
