project:
  type: website
  output-dir: docs
  
website:
  title: "Nathan Bresette's Portfolio"
  navbar:
    left:
      - href: aboutme_index.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: consulting.qmd
        text: Consulting
      - href: datafest.qmd
        text: DataFest
      - href: Resume.qmd
        text: Resume
          
  
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Nathan Bresette"

format:
  html:
    theme: Cyborg
    toc: true

editor: source

