project:
  type: website
  output-dir: docs
  
website:
  title: "Nathan Bresette's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - text: Projects
        menu: 
          - href: projects.qmd
            text: Project 1
          - href: projects.qmd
            text: Project 2
      - text: Consulting
        menu: 
          - href: projects.qmd
            text: Project 1
          - href: projects.qmd
            text: Project 2
      - text: DataFest
        menu: 
          - href: projects.qmd
            text: Project 1
          - href: projects.qmd
            text: Project 2
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/YOURUSERNAME/YOURREPO
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Nathan Bresette"

format:
  html:
    theme: Cyborg
    toc: true

editor: source

